### ISSUE TITLE
امضای بسته صحیح نمی باشد

### ISSUE THREAD

**Issue by mortezaa** [Snapp-Market-Pro/moadian#10]
سلام برای دریافت توکن خطای "امضای بسته صحیح نمی باشد" میگیریم.اشکال از کجاست؟

**Comment by rahimi-ali** [comment]
Are you using the latest version? Version 1.0.16 is the latest and it has fixed an issue with aes key encryption

**Comment by mortezaa** [comment]
Yes using the latest version

**Comment by rahimi-ali** [comment]
As we have tested the symmetric key encryption and are sure it is functioning properly and the fact that AES key is generated on the fly the only other parameter invloved is the `taxOrgPublicKey` you have provided. I suggest checking you public/private key pair.

**Comment by rahimi-ali** [comment]
I suggest using the Reference Java SDK tests provided by the tax org to verify that your public/private key are working without worrying about issues in this package. If they are working in the Java SDK and won't work here we can investigate the issue further.

Also, you can check the keys available in your account and verify you have the right keys.

**Comment by aghasi** [comment]
> I suggest using the Reference Java SDK tests provided by the tax org to verify that your public/private key are working without worrying about issues in this package. If they are working in the Java SDK and won't work here we can investigate the issue further.
> 
> Also, you can check the keys available in your account and verify you have the right keys.

where is the Reference Java SDK tests provided by the tax org?

**Comment by rahimi-ali** [comment]
https://drive.google.com/file/d/1kg1bTV5F3DUc0-ZjlUPn1RltDa0e4D9v
