### ISSUE TITLE
Missing params

### ISSUE THREAD

**Issue by alireza-a2f** [Snapp-Market-Pro/moadian#11]
It seems that the following params are missing in the header of request:
- cdcn
- cdcd
- tonw
- torv
- tocv

And the following params are missing from the body:
- nw
- ssrv
- sscv

**Comment by AmirRezaM75** [comment]
I couldn't find these params  in a technical document (‫‪RC_TICS.IS_V1.1‬‬) provided to us. They are present in ‫‪RC_IITP.IS‬‬ ‫‪_V6.2‬‬ document and I'm not sure which one is reliable.
Have you used them yourself?

**Comment by alireza-a2f** [comment]
Currently I'm using RC_IITP.IS _V6.3 which was published in Farvardin 1402. This is the most recent instruction I could find. I guess these fields were added in this update. I haven't used these params in my case but as I was checking out this package, I found these missing params and suggested for improvements.

**Comment by mmdt12** [comment]
**RC_IITP.IS _V6.4**  was published in Khordad 1402 and these params  were described in it

**Comment by Mohammad-Bagher-Hosseini** [comment]
In src/Dto/Packet.php line 154 is an error because the src\Dto\PacketDataInterface.php does not have toArray() method, this error can be seen in other places. In src\Services\EncryptionService.php line 64 rsa does not have the encrypt() method.

**Comment by rahimi-ali** [comment]
added in #32
