### ISSUE TITLE
شناسه کلید رمزنگاری اشتباه است

### ISSUE THREAD

**Issue by CyberDepot** [Snapp-Market-Pro/moadian#12]
دریافت توکن با موفقیت انجام میشود، هنگام ارسال صورتحساب خطای 4008 دارم
مشکل از کجاست؟

**Comment by rahimi-ali** [comment]
Hi,
Please follow the instructions in #10 to verify that your public private key pair are correct using the official Java SDK

What I can say about this library is that the encryption is working as we have used it in production with no issues and it is more likely that one of the parameters you are providing is not correct.

**Comment by CyberDepot** [comment]
i'm sure about parameters
i use this package and that's work correctly

[https://github.com/Jooyeshgar/moadian](url)

**Comment by mortezaa** [comment]
> i'm sure about parameters i use this package and that's work correctly
> 
> [https://github.com/Jooyeshgar/moadian](url)

Did you sent any Succussed invoice with any of this packages?

**Comment by rahimi-ali** [comment]
We have successfully sent invoices with the package.
The only advice I can give is
1. use latest tag (1.0.16 at the moment)
2. ensure public and private key are correct and have the right format
public key should look like this:
```
-----BEGIN PUBLIC KEY-----
XXXXXXXXXXXXXXXXXX
-----END PUBLIC KEY-----
```
and private key should look like this:
```
-----BEGIN PRIVATE KEY-----
XXXXXXXXXXXXXXXXXXXX
-----END PRIVATE KEY-----
```

**Comment by mortezaa** [comment]
![image](https://github.com/Snapp-Market-Pro/moadian/assets/9318638/f960af3f-c744-4c4d-b3c5-cc57469c041b)

we set everything correctly but we have an error!

**Comment by CyberDepot** [comment]
> ![image](https://user-images.githubusercontent.com/9318638/238382309-f960af3f-c744-4c4d-b3c5-cc57469c041b.png)
> 
> we set everything correctly but we have an error!

Hi
i have this problem
i switch to this package and work very good

[https://github.com/Jooyeshgar/moadian](url)
