### ISSUE TITLE
Method sendInvoice return referenceNumber ...

### ISSUE THREAD

**Issue by sjt842005** [Snapp-Market-Pro/moadian#16]
Method sendInvoice return referenceNumber & uid correctly and errorCode & errorDetail is null ,
 then by method inquiryByReferenceNumber check this referenceNumber  return "ساختار متن کلید موردنظر درست نیست."
and check this  uid  return "NOT_FOUND"
{"signature":null,"signatureKeyId":null,"timestamp":1684779095,"result":[{"uid":"d703ec9d-ad48-43ce-bb3e-e7f7bfc59c18","referenceNumber":"c7546148-9d85-4625-b89e-ede6b5f327a7","errorCode":null,"errorDetail":null}]}

**Comment by rahimi-ali** [comment]
سلام
مقادیر private key و public key رو چک کنید
توجه کنید که private key همون چیزی هست که باید خودتون generate کرده باشید و تکه public رو داده باشید به سامانه
ولی public key چیزی هست که باید از خود سامانه گرفته باشید و اون چیزی نیست که در استپ بالایی generate کردید
