### ISSUE TITLE
درخواست راهنمایی خطا 4008 شناسه کلید رمزنگاری اشتباه است

### ISSUE THREAD

**Issue by spyaea2** [Snapp-Market-Pro/moadian#17]
string(236) "{"signature":null,"signatureKeyId":null,"timestamp":1685679509,"result":[{"uid":"38681ac3-1111-1111-8b40-b70942b59c71","referenceNumber":null,"errorCode":"4008","errorDetail":"شناسه کلید رمزنگاری اشتباه است"}]}"

لطفا بفرمایید این خطا چطور رفع میشه؟ متشکرم

**Comment by rahimi-ali** [comment]
سلام
مقادیر private key و public key رو چک کنید
توجه کنید که private key همون چیزی هست که باید خودتون generate کرده باشید و تکه public رو داده باشید به سامانه 
ولی public key چیزی هست که باید از خود سامانه گرفته باشید و اون چیزی نیست که در استپ بالایی generate کردید

**Comment by faridfr** [comment]
@rahimi-ali 

وقت بخیر، کلید عمومی که در پیام قبلی گفتید همون کد 5 بخشی هست که با "-" از هم جدا شده؟ چون ما توی کار پوشه یک "شناسه یکتا" میبینیم و یک "کلید عمومی و گواهی" که همون 5 بخشیه هست.

**Comment by rahimi-ali** [comment]
You can get the public key of tax org from the `INFORMATION_SERVER_GET` endpoint of moadian API.
This is a sample curl request for that endpoint (you might need to change the requestTraceId and timestamp header to current timestamp for it to work)
```bash
curl --location 'https://tp.tax.gov.ir/req/api/tsp/sync/GET_SERVER_INFORMATION' \
--header 'requestTraceId: 1654938179880' \
--header 'timestamp: 1654938179880' \
--header 'Content-Type: application/json' \
--data '{
"time": 1,
"packet": {
"uid": null,
"packetType": "GET_SERVER_INFORMATION",
"retry": false,
"data": null,
"encryptionKeyId": "",
"symmetricKey": "",
"iv": "",
"fiscalId": "",
"dataSignature":""
}
}'
```

Will include this endpoint in the SDK in future releases but at the moment you can manually run this request for one time, get a public key and use it as long as you want.

**Comment by rahimi-ali** [comment]
#30 adds the get server info method to the Moadian class which can be used instead of this curl.
