### ISSUE TITLE
I received error 4008

### ISSUE THREAD

**Issue by 313ava** [Snapp-Market-Pro/moadian#20]
Hi, first thanks. I tested the code with my username and keys and token is received successfully. But when I sent Invoice using your provided test data I got this result:
`{"signature":null,"signatureKeyId":null,"timestamp":1686410102,"result":[{"uid":"5ffc327d-7982-49d5-bb43-b2f52ca7513d","referenceNumber":null,"errorCode":"4008","errorDetail":"شناسه کلید رمزنگاری اشتباه است"}]}`

If keys are problem why token is received without problem?

**Comment by sjt842005** [comment]
public key of tax org : این فایل را از کجا بگیریم؟

آیا این فایل برای همه شرکت ها یکسان است؟

**Comment by mailed91** [comment]
> public key of tax org : این فایل را از کجا بگیریم؟
> 
> آیا این فایل برای همه شرکت ها یکسان است؟

[https://csr.orash.ir/](url)

**Comment by rahimi-ali** [comment]
You can get the public key of tax org from the `INFORMATION_SERVER_GET` endpoint of moadian API.
This is a sample curl request for that endpoint (you might need to change the requestTraceId and timestamp header to current timestamp for it to work)
```bash
curl --location 'https://tp.tax.gov.ir/req/api/tsp/sync/GET_SERVER_INFORMATION' \
--header 'requestTraceId: 1654938179880' \
--header 'timestamp: 1654938179880' \
--header 'Content-Type: application/json' \
--data '{
"time": 1,
"packet": {
"uid": null,
"packetType": "GET_SERVER_INFORMATION",
"retry": false,
"data": null,
"encryptionKeyId": "",
"symmetricKey": "",
"iv": "",
"fiscalId": "",
"dataSignature":""
}
}'
```

Will include this endpoint in the SDK in future releases but at the moment you can manually run this request for one time, get a public key and use it as long as you want.

**Comment by rahimi-ali** [comment]
#30 adds the get server info method to the Moadian class which can be used instead of this curl.
