### ISSUE TITLE
سلام برای ارسال invoice باید data signature رو خودمون بهش بدیم ؟

### ISSUE THREAD

**Issue by Alibaghaee** [Snapp-Market-Pro/moadian#21]

**Comment by rahimi-ali** [comment]
سلام خیر وقتی به کلاس Moadian بدید خودش پر میکنه

**Comment by Alibaghaee** [comment]
> سلام خیر وقتی به کلاس Moadian بدید خودش پر میکنه

$packet = (new Packet(PacketType::INVOICE_V01, $invoiceDto)) ->setFiscalId($username) ->setDataSignature(null) ->setEncryptionKeyId(null) ->setIv(null) ->setSymmetricKey(null);

اینجا من مقدار هارو به همین صورت میدم و از سامانه ارور ۴۰۰۸ دریافت میکنم که شناسه امضا مشکل داره

**Comment by rahimi-ali** [comment]
سلام احتمالا مشکل از public یا private key هست توجه کنید public key رو باید از SERVER_INFORMATION مودیان بگیرید و نباید public key خودتون باشه. نمونه curl رو میتونید در #20 ببینید و باهاش server public key رو بگیرید
