### ISSUE TITLE
Pending response 

### ISSUE THREAD

**Issue by Alibaghaee** [Snapp-Market-Pro/moadian#22]
سلام بعد از ارسال صورت حساب ، حتی بعد چندروز درخواست ما هنوز درحالت pending گیر کرده مشکل از چه چیزی می‌تونه باشه؟

**Comment by rahimi-ali** [comment]
سلام ظاهراً اخیرا سامانه مشکلاتی داشته، ما هم به عنوان صرفا کاربر سامانه اطلاعات بیشتری نداریم.
