### ISSUE TITLE
TaxId

### ISSUE THREAD

**Issue by Alibaghaee** [Snapp-Market-Pro/moadian#24]
برای taxid بعد از پردازش درخواستم ، خطای غیرمجاز بودن  دریافت میکنم از سمت سامانه،

$taxId = $this->moadian->generateTaxId(new DateTime(), 1); 

        $invoiceHeaderDto = (new InvoiceHeaderDto);

        $invoiceHeaderDto = $invoiceHeaderDto->setTaxid($taxId);

هنگام ساخت taxid باید بجای عدد یک چه عددی وجود داشته باشه 
همچنین بقیه فیلد های ارسالی در بخش سرآمد صورت حساب هم همین ارور غیرمجاز بودن رو داره

**Comment by rahimi-ali** [comment]
نکات مهم برای ساخت taxid داشتن نام کاربری صحیح است که به کلاس مودیان دادید و همچنین عدد ۱ هم شماره فاکتور ساخته شده در سیستم خودتون باید باشه. اگر warning داره ممکنه به خاطر این باشه که قبلاً مثلا فاکتور شماره ۱۰۰ رو فرستادید و الان دارید سعی می کنید فاکتور ۱ رو بزنید که می‌تونه گیر بده و اگر error هست احتمالا قبلاً فاکتور با همون شماره رو وارد کردید.
