### ISSUE TITLE
راهنمای استفاده

### ISSUE THREAD

**Issue by MeysamSabeti** [Snapp-Market-Pro/moadian#26]
سلام.این برنامه راهنمای استفاده نداره ؟ 
من هرچقدر تلاش کردم متوجه نشدم چطوری ازش استفاده کنم

**Comment by rahimi-ali** [comment]
این پکیج به درد برنامه نویس هایی می خوره که می خوان در کد خودشون به سامانه مودیان وصل شوند و بدون داشتن یک برنامه قابل استفاده نیست.

در README نحوه نصب(که مثل هر پکیج کامپوزر دیگری است) توضیح داده شده و نکاتی درباره استفاده هم گفته شده ولی برای کار با کد باید متد ها و کلاس های مربوطه را از روی کد خواند.
