### ISSUE TITLE
Absence of some methods

### ISSUE THREAD

**Issue by Mohammad-Bagher-Hosseini** [Snapp-Market-Pro/moadian#29]
In src\Dto\Packet.php line 154 is an error because the src\Dto\PacketDataInterface.php does not have toArray() method, this error can be seen in other places. In src\Services\EncryptionService.php line 64 rsa does not have the encrypt() method.

**Comment by rahimi-ali** [comment]
Yes you are correct, in reallity all the DTOs we have implement the toArray method and thats why everything has worked despite that method not being available on the interface. Will be fix in a future release soon.

**Comment by rahimi-ali** [comment]
#30 fixes this
