### ISSUE TITLE
error code 4008

### ISSUE THREAD

**Issue by fnamkhah** [Snapp-Market-Pro/moadian#31]
سلام
برای ارسال فاکتور به سامانه مودیان این خطارو میگیرم بدون هیچ توضیحی. لطفا راهنمایی بفرمایید.

{"signature":null,"signatureKeyId":null,"timestamp":1697972688,"result":[{"uid":"8fa777ba-6c56-4b40-9bfe-c1267e79dc60","referenceNumber":null,"errorCode":"4008","errorDetail":"4008"}]}

**Comment by rahimi-ali** [comment]
سلام این ارور مربوط به رمزنگاری اشتباهه که یعنی یکی از این دو مورد اشتباه است:
۱. مقدار tax org public key اشتیاهه. برای گرفتنش میتونید از getServerInformation استفاده کنید(در مثال ها هم وجود داره)
۲. مقدار private key اشتباهه که باید توجه کنید private key باید متناظر با public key ای باشید که خودتون قبلا ساختید و در سامانه بارگذاری کردید با باهاش شناسه  گرفتید
