### ISSUE TITLE
problem with taxid

### ISSUE THREAD

**Issue by Mohammad-Bagher-Hosseini** [Snapp-Market-Pro/moadian#35]
سلام خسته نباشید.
من سعی در ارسال یک فاکتور داشتم اما با ارور زیر مواجه شدم لطفا راهنمایی کنید:

"code":"0301","message":
"
مقدار فیلد «شماره مالیاتی صورتحساب» با اطلاعات سامانه منطبق نیست
"

**Comment by rahimi-ali** [comment]
سلام.
این پکیج ارتباطی با تیم فنی سامانه مودیان ندارد و ما هم صرفا از استفاده کنندگان سامانه هستیم لذا نمی تونیم به دقت دلیل تمام ارور‌ها رو بدونیم ولی این ارور تا جایی که می دونم مربوط به اتفاقی است که اخیرا افتاد و فرستادن فاکتور برای زمانی قبل از دو هفته پیش(یا یک چنین بازه ای) ممنوع شد و این ارور برای صورتحساب هایی ایجاد می شد که قدیمی هستند.
