### ISSUE TITLE
Error in vop and tvop type

### ISSUE THREAD

**Issue by Mohammad-Bagher-Hosseini** [Snapp-Market-Pro/moadian#36]
سلام خسته نباشید 
vop و tvop 
به صورت string هستند اما طبق فایل پیوست شده باید تایپ عددی داشته باشند (int, double, ...)
[Intamedia_02_RC_IITP_IS_V05-دستورالعمل-صدور-صورتحساب-الکترونیکی.pdf](https://github.com/Snapp-Market-Pro/moadian/files/13404515/Intamedia_02_RC_IITP_IS_V05-.-.-.-.pdf)

**Comment by Azare77** [comment]
تو بررسی کد اگه با فایل مربوط به body و header نگاه کنی نوع فیلد عددی هست
