### ISSUE TITLE
دریافت اطلاعات سرور

### ISSUE THREAD

**Issue by mohammadsaleh** [Snapp-Market-Pro/moadian#37]
سلام، در برخی درخواست ها مثل getServerInformation نیاز به ارسال private key نیست اما، با توجه به نحوه کد نویسی شما، توسعه دهنده رو ملزم به ارسال آن به کلاس Moadian میکنه. بنظرم بهتره راهکار بهتری برای این موضوع در نظر بگیرید

**Comment by sa-ahmadzade** [comment]
این تابع فقط 2 ورودی لازم دارد
شناسه حافظه یکتا مالیاتی و کلید خصوصی
موفق باشید
