### ISSUE TITLE
ارور ۴۰۰۸

### ISSUE THREAD

**Issue by this-mojtaba** [Snapp-Market-Pro/moadian#39]
سلام. ما در ساخت invoice به ارور کد ۴۰۰۸ بر میخوریم که ریسپانش بدین صورت است:
{"response":{"signature":null,"signatureKeyId":null,"timestamp":1709107738,"result":[{"uid":"ea6a9ab3-5a16-46aa-8f88-75205f7e4589","referenceNumber":null,"errorCode":"4008","errorDetail":"4008"}]}}

**Comment by amir-ghasemnj** [comment]
> سلام. ما در ساخت invoice به ارور کد ۴۰۰۸ بر میخوریم که ریسپانش بدین صورت است: {"response":{"signature":null,"signatureKeyId":null,"timestamp":1709107738,"result":[{"uid":"ea6a9ab3-5a16-46aa-8f88-75205f7e4589","referenceNumber":null,"errorCode":"4008","errorDetail":"4008"}]}}

عرض ادب و احترام.
منم جدیدا دارم از این کتابخونه استفاده میکنم.
مساله ای که شما خوردید بابت متغیر taxOrgKeyId داخل فایل send-invoices.php هست.
به ترتیب زیر مراحل رو پیش برید انشاءالله موردتون رفع میشه:
۱. فایل get-tax-org-public-key.php رو باز کنید انتهای فایل میبینید که ساختار خروجی وب‌سرویس مودیان رو نشون میده که به شکل زیر هست:
`{
    "signature": null,
    "signatureKeyId": null,
    "timestamp": 11111111111,
    "result": {
        "uid": "XXXX",
        "packetType": "SERVER_INFORMATION",
        "data": {
            "serverTime": 11111111111,
            "publicKeys": [
                {
                    "key": "XXXX",
                    "id": "XXXX",
                    "algorithm": "RSA",
                    "purpose": 1
                }
            ]
        },
        "encryptionKeyId": null,
        "symmetricKey": null,
        "iv": null
    }
}`
۲. خروجی وب‌سرویس رو var_dumpبگیرید.
۳. مقدار فیلد id داخل publicKeys رو باید جای متغیر taxOrgKeyId قرار بدید.
مشکلی بود بگید که باهم پیش بریم.

خودم یک مشکل بدی خوردم برای اینکه یک سره سامانه مودیان میگه "مقدار فیلد «مبلغ مالیات بر ارزش افزوده(KS)» از لحاظ قواعد محاسباتی و منطقی معتبر نیست" و نمیدونم واقعا چکار کنم.

**Comment by amir-ghasemnj** [comment]
ضمنا هرچی کم و کسر داری از وب‌سایت زیر تکمیل کن
http://tax.withink.ir/sm-developer/
