### ISSUE TITLE
The cryptographic key ID is incorrect

### ISSUE THREAD

**Issue by hadi60** [Snapp-Market-Pro/moadian#4]
when I use my own key ID, It says:
"errorCode": "4008"
"errorDetail": "شناسه کلید رمزنگاری اشتباه است"

when I use sample key ID
$orgKeyId = '6a2bcd88-a871-4245-a393-2843eafe6e02';
It's OK, but in inquiry I get this error:
"ساختار متن کلید موردنظر درست نیست."

1 - I got my key ID from the tp.tax.gov.ir (شناسه کلید امضا ), is it correct?
2 - Do you have a solution?

**Comment by rahimi-ali** [comment]
Unfortunately we don't have access to the sandbox area at the moment so we can't test and fix the issue until we get it working. Will check the issue and fix it if it exists in the following week.

**Comment by hadi60** [comment]
Is there a sandbox available?
My main question is whether I obtained the key ID from the correct place?

**Comment by rahimi-ali** [comment]
Yes there is a sandbox available you can request access to it and use it for testing purposes.
The key ID you are using seems correct and the issues seems to be in the symmetric key encryption. Will work on a fix as soon as we get access to the sandbox

**Comment by hadi60** [comment]
Where can I request access?
No one is guiding me or has any knowledge about it.
Where exactly are you calling?

**Comment by rahimi-ali** [comment]
Fixed in https://github.com/Snapp-Market-Pro/moadian/commit/57207692aed92a6ccc6e3c87afb6d104ca53c327

Regarding the sandbox I cannot help you because I have not been in direct contact with the tax organization.
