### ISSUE TITLE
Fatal error: Uncaught GuzzleHttp\Exception\ClientException: Client error: `401 Unauthorized`

### ISSUE THREAD

**Issue by mohammad-mahdi-hodayan** [Snapp-Market-Pro/moadian#41]
Fatal error: Uncaught GuzzleHttp\Exception\ClientException: Client error: `POST https://sandboxrc.tax.gov.ir/req/api/self-tsp/sync/GET_TOKEN` resulted in a `401 Unauthorized` response in C:\wamp64\www\mm\vendor\guzzlehttp\guzzle\src\Exception\RequestException.php on line 113

درود فراوان / ارور بالا بعد از اجرای کد دریافت میشه.  با کد های python تست گرفتم از public & private کلید ها و همچنین username 
متغییر taxOrgPublicKey رو هم از getServerInformation قسمت id برداشتم و ارور 401 دریافت میکنم همچنان... 

متوجه نمیشم مشکل از کجاست ممنون میشم راهنمایی کنید.

**Comment by CyberDepot** [comment]
منم همین خطا رو دارم میگیرم، اتفاق خاصی افتاده؟ شما تونستی مشکل رو حل کنی؟

**Comment by mohammad-mahdi-hodayan** [comment]
> منم همین خطا رو دارم میگیرم، اتفاق خاصی افتاده؟ شما تونستی مشکل رو حل کنی؟

سلام وقت خوش. مشمل از امضای بسته بود، کلید های public و private رو بروزرسانی کنید داخل کد هم تغییراتی باید اعمال بشه. البته نهایتا من متوجه شدم با پایتون بهتر میشه اجراش کرد. پیشنهاد میکنم مودیان رو سرچ کنید تو گیت هاب و از پکیج پایتونی که نوشته شده استفاده کنید، نهایتا با php فراخوانی کنید اون کد پایتون رو.

**Comment by CyberDepot** [comment]
من پکیج رو بررسی کردم، تغییر خاصی در کدها ندیدم به جز چند مورد که float شده بود
شما چه تغییری تو کد دادین؟

**Comment by sa-ahmadzade** [comment]
$info = $moadian1->getServerInformation();
 $publicKey = $info['result']['data']['publicKeys'][0]['key'];
 $taxOrgKeyId = $info['result']['data']['publicKeys'][0]['id'];
بعد از اولین اتصال این دو مقدار رو جایی ذخیره کن، سپس در درخواست های بعدی این دو مقدار رو همراه درخواست ایجاد کلاس بفرست.کار می کنه. براتون حل نشد [@boyishprogrammer](https://t.me/boyishprogrammer)  تلگرام پیام بده
