### ISSUE TITLE
pv در اطلاعات پرداخت وجود ندارد

### ISSUE THREAD

**Issue by DavoodGhanbarpour** [Snapp-Market-Pro/moadian#45]
طبق [داکیومنت](https://www.intamedia.ir/Portals/0/news/Terminals/RC_IITP_IS_V07%20_1.pdf?ver=wPeI1sViL-DZOif78cl-pA%3d%3d) باید در قسمت پرداخت ویژگی مبلغ پرداختی(pv) ارسال گردد

**Comment by DavoodGhanbarpour** [comment]
همچنین سه ویژگی جدید در قسمت بدنه اضافه شده که در پکیج فعلی وجود ندارند. 
pspd - تفاوت نرخ خرید و فروش ارز / کارمزد فروش ارز
cui - عیار
tinc - شماره اقتصادی آژانس

**Comment by rahimi-ali** [comment]
Since we are going to archive this repository you can fork it and make the required changes
