### ISSUE TITLE
4103 ساختار متن کلید موردنظر درست نیست.

### ISSUE THREAD

**Issue by hadishahpuri** [Snapp-Market-Pro/moadian#8]
بعد از ثبت invoice وقتی refrence_number رو در API INQUIRY_BY_REFERENCE_NUMBER ارسال میکنم این خطا رو میده
        "status" => "FAILED"
        "data" => array:1 [
          0 => array:3 [
            "code" => "4103"
            "msg" => "ساختار متن کلید موردنظر درست نیست."
            "detail" => null
          ]
        ]

**Comment by rahimi-ali** [comment]
Fixed in https://github.com/Snapp-Market-Pro/moadian/commit/57207692aed92a6ccc6e3c87afb6d104ca53c327

**Comment by mortezaa** [comment]
we have same problem any solution?
