### ISSUE TITLE
خطایی در واکشی اطلاعات  خریدار رخ داده است

### ISSUE THREAD

**Issue by hadishahpuri** [Snapp-Market-Pro/moadian#9]
پس از ارسال درخواست ثبت صورتحساب وقتی که وضعیت درخواست رو چک میکنم این خروجی رو برمیگردونه:
        "data" => array:4 [
          "confirmationReferenceId" => null
          "error" => array:1 [
            0 => array:3 [
              "code" => "5604"
              "msg" => "خطایی در واکشی اطلاعات  خریدار رخ داده است"
              "detail" => null
            ]
          ]
          "warning" => []
          "success" => false

اطلاعات خریدار و فروشنده هم به صورت کامل در فیلد های: tins , bid , tinb وارد شده

**Comment by rahimi-ali** [comment]
Unfortunately I cannot help you with the errors thrown by the API as we are not it's developers and the documentation is not very good either especially regarding validation errors.

I suggest you check the buyer tax id and make sure you have the correct information.

As this issue does not concern the SDK I will close the issue for now.
